### ISSUE TITLE
I tried to play, it refused.

### ISSUE THREAD

**Issue by Ayria** [AdrianEddy/AIMPYouTube#14] opened 2017-08-16 19:23 UTC
I tried with several youtube links. I got this every time.
Am I doing something wrong maybe?

File: youtube://OIh3nO6-V_A/Metallica - Whiskey in the jar.mp4
Code: -1 (FFFFFFFF)
Message: Unknown Error
-------------------------
HTTP/1.1 403 Forbidden
Last-Modified: Wed, 02 May 2007 10:26:10 GMT
Content-Type: text/plain
Content-Length: 0
Connection: close
X-Content-Type-Options: nosniff
Date: Wed, 16 Aug 2017 19:21:51 GMT
Server: gvs 1.0

**Comment by Titanic4** [comment] 2018-08-24 13:11
I've got similar issue as well - I think it's caused by daily quota being exceeded or something like that.

**Comment by T1mL3arn** [comment] 2019-01-04 05:22
Have the same.

**Comment by AdrianEddy** [comment] 2020-01-18 13:51
Fixed in latest commits, binary release will be updated soon

**Closed as completed by AdrianEddy** 2020-01-18 13:51 UTC
